version: '3'

services:
  # Backend API service
  api:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root_password
      - DB_NAME=alumni_network
      - JWT_SECRET_KEY=docker_jwt_secret_key
      - SECRET_KEY=docker_flask_secret_key
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    restart: always
    volumes:
      - ./:/app

  # MySQL Database
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=alumni_network
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data: 